### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bserem** [stsourlidakis/postgreSQL-dropbox-backup#2]
1) Start with `#!/bin/bash`
2) gzip the resulting file
3) if the script is going to be executed automatically you might want to use some sort of logfile, to see if all work as expected

**Comment by stsourlidakis** [comment]
Thanks for the suggestions
1. [0d96def](https://github.com/stsourlidakis/postgreSQL-dropbox-backup/commit/0d96deff81adbff2ea208bbd2f611fde71a928bf)
2. [4887be2](https://github.com/stsourlidakis/postgreSQL-dropbox-backup/commit/4887be2cbc41cb96c93b4b0426bcde4bfda5bf20)
3. I'm not sure how to catch all possible errors(pg_dump/API response) but I'll try to figure it out, feel free to PR

**Comment by bserem** [comment]
I've never transfered anything to dropbox via Curl, so I do not know the possible errors. Haven't used postgre either :)

But the bash part looks better now. If you want to take it further (in order to check more of what can be done) you can even calculate a MD5/SHA hash and store it somewhere (before gzip) so as to be able to check the intergrity of your backup.

In general (and totally outside of what you are trying to achive here) I prefer to dump backups with SCP into a remote server than to rely on dropbox. There, with SSH commands you can do all sorts of things.

Keep on! Bash is really handy
